import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import Dashboard from '../components/Dashboard'
import axios from 'axios'
import nookies from 'nookies'

const inter = Inter({ subsets: ['latin'] })

export default function Home({tasks}) {
  return (
    <>
      <Head>
        <title>Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Dashboard tasks={tasks}/>
    </>
  )
}
export const getServerSideProps=async(ctx)=>{
  const cookies = nookies.get(ctx)
  const response=await axios.get("https://task-app-269i-mobi7am1h-sanj1997.vercel.app/api/tasks",{
    headers:{
      authorization:cookies.accessToken
    }
  })
  const tasks=response.data.data
  return {
    props:{
      tasks
    }
  }
}